# 指定项目名
spring:
  application:
    name: producer

# 指定端口号
server:
  port: 7012


# 向eureka的server注册服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7011/eureka/,http://localhost:7021/eureka/,http://localhost:7022/eureka/

  instance:
    # 每隔1秒钟 向注册中心发一次心跳 证明自己还活着
    lease-renewal-interval-in-seconds: 1
    # 告诉注册中心 超过2秒未发送心跳 代表已宕机 可以剔除
    lease-expiration-duration-in-seconds: 2
